apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: asia-southeast2-docker.pkg.dev/poc-bjb-mlff/test-repo-bjb-application/garden-app-backend:32
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATABASE
          value: richard
        - name: PGUSER
          value: richard
        - name: PGPASSWORD
          value: mysecretpassword
        - name: PGHOST
          value: 0.0.0.0
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 90
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 1
          successThreshold: 2
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 90Mi
        nodeSelector:
          cloud.google.com/gke-nodepool: "app-be-dev-node-pool-1"
        securityContext:
          allowPrivilegeEscalation: false
