# apiVersion: v1
# kind: Service
# metadata:
#   name: api
# spec:
#   type: ClusterIP
#   clusterIP: 172.16.8.35
#   selector:
#     app: api
#   ports:
#   - port: 80
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    cloud.google.com/load-balancer-type:"Internal"
spec:
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 172.16.8.35
  selector:
    app: api
  ports:
  - port: 80 
    targetPort: 8080