# apiVersion: v1
# kind: Service
# metadata:
#   name: api-address
# spec:
#   type: ClusterIP
#   clusterIP: 172.16.8.35
#   selector:
#     app: api
#   ports:
#   - port: 80
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: api-loadbalancer
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.1.242
  selector:
    app: api
  ports:
  - port: 80 
    targetPort: 8080