# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: api
#   name: api
# spec:
#   type: ClusterIP
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     app: api

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer 
  selector:
    app: api
  ports:
  - port: 80 
    targetPort: 8080